### ISSUE TITLE
Support multiple “slides” for “TV mode”

### ISSUE THREAD

**Issue by andrew-boyd** [wearebraid/be.camp#14]
It would be helpful to have the TV mode that’s currently being used for the schedule to be able to host and rotate through other content as well. Specifically the code of conduct link to keep it fresh in the mind of all attendees.

**Comment by dylansheffer** [comment]
Likely going to go with a slides.com approach where we load the schedule into an iFrame slide and then have a few announcements, the COC and repeat.

**Comment by andrew-boyd** [comment]
@dylansheffer I'm going to close this issue since slides.com showing the event schedule as one of the slides solves it and the only responsibility of the website will be to serve up a sensible TV UI for the schedule, which it already does.
