### ISSUE TITLE
We're the Cville tech community, let's score 100 across the board on a lighthouse audit!

### ISSUE THREAD

**Issue by andrew-boyd** [wearebraid/be.camp#15]
# Problem
Currently the PWA and Accessibility scores for be.camp have some available recommendations from a lighthouse audit run on desktop.

# Suggested Solution
Follow the recommendations in the lighthouse audit results to score 100 across the board (or as close as possible) when running a desktop audit with no throttling.

**Comment by dylansheffer** [comment]
I'll take a look at this
