### ISSUE TITLE
Add link to Charlottesville Tech calendar in tasteful way

### ISSUE THREAD

**Issue by andrew-boyd** [wearebraid/be.camp#18]
This handy calendar of tech events exists: https://calendar.google.com/calendar/embed?showTitle=0&height=600&wkst=1&bgcolor=%23FFFFFF&src=nqd22f84k29tmgj0ububdgbbjo@group.calendar.google.com&color=%23125A12&ctz=America/New_York

We should leverage it to encourage attendees to not only have the beCamp / beSwarm dates on their calendar, but to be more aware of the larger tech community happenings.

It would be great to have this implemented as an external link. Would not want to include an ugly embed of the google calendar itself on the site.

**Comment by andrew-boyd** [comment]
Closing as out of scope unless someone objects.

**Comment by dylansheffer** [comment]
That works for me. I have been meaning to ask if you had any ideas on accomplishing it because I haven't been able to think of anything lol
