### ISSUE TITLE
"Name-only" sponsors are not showing up on the website

### ISSUE THREAD

**Issue by andrew-boyd** [wearebraid/be.camp#24]
<img width="688" alt="Screen Shot 2019-09-06 at 4 18 05 PM" src="https://user-images.githubusercontent.com/2946356/64457942-0ce3cf80-d0c2-11e9-80d6-aeb834e9d05f.png">

Multiple exist in Airtable but they are not being reflected on the front-end. This is likely just a changed field name that needs to be updated in the front-end code.

**Comment by dylansheffer** [comment]
Found the issue. Putting in a pull request in a minute
