### ISSUE TITLE
Linking to an anchor works once loaded, but not on first page load.

### ISSUE THREAD

**Issue by rduplain** [wearebraid/be.camp#9]
**Describe the bug**
Linking to an anchor works once loaded, but not on first page load. If you have the site loaded, and follow a link to "#something", it works as expected if "#something" exists. However, if you link externally to "#something", the anchor link has no effect.

**To Reproduce**
1. Open a new browser tab.
2. Open <https://be.camp/faqs#faq7>.
3. Notice that the page loads from the top of the FAQ section, and does not position over the anchor.

**Additional context**
It _does_ work as expected when you change the page location with a valid anchor, once the page has loaded.

**Comment by rduplain** [comment]
You can just follow the link from here to reproduce: https://be.camp/faqs#faq7

**Comment by andrew-boyd** [comment]
Fixed by: https://github.com/wearebraid/be.camp/commit/6bc97b8955aed7c0a62e3c0f29edc516412e1b12
